set -e
set -x

export PYTHONPATH=$PWD
export DETECTRON2_DATASETS=${your_data_path}

MODEL_DIR=${your_model_path}

CUDA_VISIBLE_DEVICES=0,1,2,3 python train_net_fcos.py \
  --config configs/Base-FCOS-TSP.yaml \
  --num-gpus 4 \
  --dist-url "tcp://localhost:23456" \
  OUTPUT_DIR ${MODEL_DIR} \
  MODEL.WEIGHTS "detectron2://ImageNetPretrained/MSRA/R-50.pkl" \
  MODEL.RESNETS.DEPTH 50 \
  MODEL.MY_ROI_BOX_HEAD.DIM_FEEDFORWARD 2048 \
  MODEL.FCOS.RANDOM_PROPOSAL_DROP True \
  MODEL.FCOS.RANDOM_PROPOSAL_DROP_LOWER_BOUND 0.7 \
  MODEL.FCOS.USE_OBJ_LOSS True \
  MODEL.FCOS.ONLY_REWEIGHT_FG True \
  SOLVER.IMS_PER_BATCH 16 \
  SOLVER.STEPS "(180000, 240000)" \
  SOLVER.MAX_ITER 270000 \
  SOLVER.CHECKPOINT_PERIOD 10000 \
  SOLVER.BASE_LR 0.01 \
  SOLVER.TRANSFORMER_MULTIPLIER 0.01 \
  MODEL.FCOS.INFERENCE_TH_TEST 0.0 \
  MODEL.FCOS.INFERENCE_TH_TRAIN 0.0 \
  MODEL.FCOS.GIOU_WEIGHT 2.0 \
  MODEL.FCOS.PREDICT_WITHOUT_CTR True \
  MODEL.FCOS.CLASS_DENORM_TYPE "mixed_2x"
