MODEL:
  META_ARCHITECTURE: "MyFCOS"
  BACKBONE:
    NAME: "build_resnet_myfpn_backbone_v2"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  OPTIMIZER: "HYBRID"
  BASE_LR: 0.01
  BOTTOM_UP_MULTIPLIER: 1.0
  TRANSFORMER_MULTIPLIER: 0.02
  WEIGHT_DECAY: 0.0001
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
TEST:
  EVAL_PERIOD: 5000
VIS_PERIOD: 500
SEED: 42
